"""Centralised configuration constants for the pipeline.

All tunable thresholds and the generation seed live here (see spec §13).
"""

# ---- Deterministic generation -------------------------------------------------
SEED = 20250311
POPULATION = 1000  # synthetic customers

# ---- Counted defect injection (exact target counts, non-round by design) -------
INJECTION_COUNTS = {
    "allocation": 37,          # feeds rule #1 wrongful notice
    "stale_unswept_credit": 12,  # feeds rule #2 orphaned credit
    "statement_gap": 9,        # feeds rule #3
    "duplicate_invoice": 6,    # feeds rule #5
    "dishonour": 4,            # feeds rule #4
}
# A small tracked-overlap group that is hit by TWO defect families, exercising
# rule independence (both rules must fire on the same customer without conflation).
TRACKED_OVERLAP = 3

# ---- Notice / dunning rule -----------------------------------------------------
GRACE_DAYS = 7          # naive notice fires at due_date + grace_days
# Credit becomes "orphaned" once unapplied for longer than this window.
ORPHAN_DAYS = 30

# ---- Statement continuity ------------------------------------------------------
GAP_THRESHOLD_DAYS = 3  # rule #3: gap between consecutive statements > this
AMOUNT_TOLERANCE_RATIO = 0.01  # rule #5: abs(Δ) <= max($1, 1%)
AMOUNT_TOLERANCE_MIN_DOLLARS = 1.0

# ---- Severity escalation ------------------------------------------------------
# Defaults to $100; honestly NOT anchored to provider evidence (unlike GRACE_DAYS).
# Purely configurable defaults — see spec §6 / CONTEXT.md "Severity escalation principle".
NOTICE_ESCALATION_THRESHOLD = 100.00   # rule #1: high -> critical
DUPLICATE_ESCALATION_THRESHOLD = 100.00  # rule #5: medium -> high

# ---- Severity map (base) ------------------------------------------------------
SEVERITY_BASE = {
    1: "high",
    2: "warning",
    3: "medium",
    4: "critical",
    5: "medium",
}

# ---- Optional LLM paraphrase layer --------------------------------------------
NIM_ENDPOINT = "https://integrate.api.nvidia.com/v1"
NIM_MODEL_ID = "meta/llama-3.3-70b-instruct"  # pinned; only rephrases, never invents
NIM_MAX_CALLS = 40  # shared per-key rate cap — calls hard-capped
NIM_API_KEY_ENV = "NIM_API_KEY"

# ---- Directory layout ----------------------------------------------------------
FIXTURE_DIR = "fixtures"     # committed Bronze CSV fixtures
DATA_DIR = "data"            # Delta tables (gitignored, regenerated by pipeline)
DASHBOARD_PATH = "dashboard.html"
MANIFEST_PATH = "ground_truth_manifest.csv"
