"""Deterministic Plotly dashboard generation (pipeline's final stage).

Constraints (spec §8): a single self-contained ``dashboard.html`` with inline
Plotly.js (no CDN), fixed ``div_id``s in a fixed order (``notices-by-rule``,
``flags-over-time``, ``drilldown-table``), all text baked in at generation time
(view-time never calls anything), and byte-stable output so a regenerate-and-diff
CI check is meaningful. Never depends on the optional LLM layer.
"""
from __future__ import annotations

import os

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Fixed div ids, in the exact order they must appear in the HTML.
DIV_IDS = ["notices-by-rule", "flags-over-time", "drilldown-table"]
RULE_LABELS = {1: "R1 wrongful notice", 2: "R2 orphaned credit", 3: "R3 statement gap",
               4: "R4 dishonour", 5: "R5 duplicate invoice"}


def _notices_by_rule(df: pd.DataFrame) -> go.Figure:
    counts = df["rule_id"].value_counts().reindex(sorted(RULE_LABELS)).fillna(0).astype(int)
    fig = go.Figure(
        data=[go.Bar(x=[RULE_LABELS[r] for r in counts.index], y=counts.values)],
        layout=go.Layout(
            title="Detected anomalies by rule",
            xaxis={"title": "Rule"},
            yaxis={"title": "Count"},
            height=420,
        ),
    )
    return fig


def _flags_over_time(df: pd.DataFrame) -> go.Figure:
    months = df["flag_date"].astype(str).str[:7].value_counts().sort_index()
    fig = go.Figure(
        data=[go.Scatter(x=list(months.index), y=months.values, mode="lines+markers")],
        layout=go.Layout(
            title="Anomalies flagged over time (by month)",
            xaxis={"title": "Month"},
            yaxis={"title": "Flags"},
            height=420,
        ),
    )
    return fig


def _drilldown_table(df: pd.DataFrame) -> go.Figure:
    view = df.sort_values(["severity", "customer_id", "rule_id"]).copy()
    view["rule"] = view["rule_id"].map(RULE_LABELS)
    view["flag_date"] = view["flag_date"].astype(str)
    table = go.Figure(
        data=[
            go.Table(
                header=dict(
                    values=[
                        "Customer",
                        "Rule",
                        "Severity",
                        "Amount ($)",
                        "Invoice",
                        "Date",
                        "Explanation",
                    ]
                ),
                cells=dict(
                    values=[
                        view["customer_id"],
                        view["rule"],
                        view["severity"],
                        view["amount"].round(2),
                        view["invoice_id"].fillna(""),
                        view["flag_date"],
                        view["explanation"],
                    ]
                ),
            )
        ],
        layout=go.Layout(title="Flagged accounts drilldown", height=700),
    )
    return table


def render(df: pd.DataFrame, out_path: str) -> str:
    """Render the three figures into one self-contained HTML file. Returns the path."""
    figs = [_notices_by_rule(df), _flags_over_time(df), _drilldown_table(df)]

    chunks = []
    for i, (fig, div_id) in enumerate(zip(figs, DIV_IDS)):
        include = "inline" if i == 0 else False
        chunks.append(
            fig.to_html(
                full_html=False,
                include_plotlyjs=include,
                div_id=div_id,
                config={"displayModeBar": False},
            )
        )

    html = (
        "<!DOCTYPE html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">\n"
        "<title>Superloop billing-anomaly detector — flagged accounts</title>\n"
        "</head><body>\n"
        "<h1>Superloop billing-anomaly detector</h1>\n"
        "<p>Deterministic dashboard generated by the pipeline (see spec §8).</p>\n"
        + "\n".join(chunks)
        + "\n</body></html>\n"
    )

    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(html)
    return out_path


def render_from_spark(flags_df, out_path: str = None) -> str:
    """Collect a Spark flagged DataFrame and render. Returns output path."""
    if out_path is None:
        from . import config

        out_path = config.DASHBOARD_PATH
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    pdf = flags_df.toPandas()
    return render(pdf, out_path)
